### PR TITLE
new-print validation fix

### LINKED ISSUE #65: Add validation to `/new-print`
Currently a user doesn't have to complete any of the drop down values in `/new-print` before pressing NEXT.  

Let's add some validation, so they cannot go to the next page unless they have chosen an option for each of the drop-downs.

### PR DESCRIPTION
**Pull request by okarem**
closes #65

### CODE REVIEW

File: src/components/curing-pages/Sensors-list-page/Sensors-list/list.jsx [hunk 1]
```diff
@@ -29,7 +29,7 @@ function List({ Curing = true }) {
   React.useEffect(() => {
     fetch(`${endpointUrl}/get-sensors`)
       .then(res => res.json())
-      .then(res => setList(res.sensors));
+      .then(res => setList(res.sensors.reverse()));
```
Comment (jamiecoe) [inline src/components/curing-pages/Sensors-list-page/Sensors-list/list.jsx]: Call this `data` rather than `res`

File: src/components/new-print-page/new-print-form/print-form.jsx [hunk 2]
```diff
@@ -17,6 +18,19 @@ const PrintForm = () => {
...
+  const handleSubmit = () => {
+    if (
+      Object.values(info).reduce(
+        (acc, curr) => (acc = acc && curr != null),
+        true
+      )
+    ) {
+      history.push("/new-print-page-2");
+    } else {
+      alert("Insufecient Input");
```
Comment (jamiecoe) [inline src/components/new-print-page/new-print-form/print-form.jsx]: Small typo - Insufficient

File: src/components/sign-up/sign-up.jsx [hunk 3]
```diff
@@ -21,7 +21,7 @@ export default () => {
       const sendUserDetails = { ...user };
       delete sendUserDetails.confirmPassword;
       fetch(`${endpointUrl}/sign-up/${token}`, {
-        method: "POST",
+        credentials: "include",
```
Comment (jamiecoe) [inline src/components/sign-up/sign-up.jsx]: This still needs to be a POST

And we don't need to send the cookie here, so you can remove `credentials: "include"`

**Review by jamiecoe — CHANGES_REQUESTED** [review]

File: src/components/curing-pages/Sensors-list-page/Sensors-list/list.jsx [hunk 4]
```diff
@@ -29,7 +29,7 @@ function List({ Curing = true }) {
   React.useEffect(() => {
     fetch(`${endpointUrl}/get-sensors`)
```
Comment (jamiecoe) [inline src/components/curing-pages/Sensors-list-page/Sensors-list/list.jsx]: We need `credentials: "include"` here as well - the BE needs to check if jwt cookie is authorised before returning data.

File: src/components/edit-drop-down-lists/edit-drop-down-lists-page.jsx [hunk 5]
```diff
@@ -18,7 +18,7 @@ const EditDropDownListsPage = () => {
     fetch(`${endpointUrl}/print-inputs-options`)
```
Comment (jamiecoe) [inline src/components/edit-drop-down-lists/edit-drop-down-lists-page.jsx]: We need credentials: "include" here as well - the BE needs to check if jwt cookie is authorised before returning data.

File: src/components/edit-drop-down-lists/edit-drop-down-lists-page.jsx [hunk 6]
```diff
@@ -18,7 +18,7 @@ const EditDropDownListsPage = () => {
...
       .then(res => res.json())
       .then(data => {
-        setOptions(Object.keys(data));
+        setOptions(Object.keys(data).filter(item=>item!="_id"));
```
Comment (jamiecoe) [inline src/components/edit-drop-down-lists/edit-drop-down-lists-page.jsx]: Can you run `Prettier` while you're here 🙏 💅

**Review by jamiecoe — CHANGES_REQUESTED** [review]

**Comment by jamiecoe** [comment]
@okarem We also need to include credentials on `/get-all-users` and `/print-inputs-options` (inside `print-form.jsx`)

File: src/components/edit-drop-down-lists/edit-drop-down-lists-page-2.jsx [hunk 7]
```diff
@@ -50,17 +50,24 @@ const EditDropDownListsPage2 = () => {
...
-          let updatedOptions=JSON.parse(JSON.stringify(ddlOptions));
-          updatedOptions.values.push(newOption)
-          setDdlOptions(updatedOptions)}}>ADD</button></div>
+        <div className="add-bar-button">
+          <button
+            onClick={() => {
+              const newOption = {};
+              newOption.value = inputValue.replace(/\s+/g, "_").toLowerCase();
+              newOption.label = inputValue;
+              let updatedOptions = JSON.parse(JSON.stringify(ddlOptions));
```
Comment (jamiecoe) [inline src/components/edit-drop-down-lists/edit-drop-down-lists-page-2.jsx]: `const` instead of `let`

**Review by jamiecoe — APPROVED** [review]
